### ISSUE TITLE
Buffer out of range exception

### ISSUE THREAD

**Issue by vitorsilvalima** [grs/rhea#26]
Hi, I get an exception when I run the following code:

`const container = require('rhea');

container.on('connection_open', function (context) {
    context.connection.open_receiver('TEST');
    
});

container.on('message', function (context) {
    console.log(context.message.body);
});

container.connect({'port':5672});`

The exception message conveys that the buffer is out of range. The exception error is the following:
`buffer.js:821
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:821:11)
    at Buffer.readUInt32BE (buffer.js:895:5)
    at Transport.read (/home/vlima/Documents/development/nodejs/node-stomp-ws/node_
modules/rhea/lib/transport.js:74:33)
    at Connection.input (/home/vlima/Documents/development/nodejs/node-stomp-ws/nod
e_modules/rhea/lib/connection.js:370:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)`

**Comment by grs** [comment]
I need a little more information to be able to reproduce your problem. What are you connecting to? Does the TEST queue (or topic) exist? Does it have a message and if so how was that message sent?

**Comment by vitorsilvalima** [comment]
I'm using the Artemis Broker, the enterprise version that is not yet released. This queue is already created on the broker and it has more than 1000 messages waiting to be consumed. The payload for each message is  "test message: number"
![screenshot from 2017-03-30 12-07-06](https://cloud.githubusercontent.com/assets/9752658/24511105/723f6374-1541-11e7-8428-854c5f19fc53.png)
