### ISSUE TITLE
Missing options.js file

### ISSUE THREAD

**Issue by kornys** [grs/rhea#30]
$ node simple_send.js --help
module.js:471
    throw err;
    ^

Error: Cannot find module './options.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dkornel/redhat/repos/rhea/examples/simple_send.js:22:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by kornys** [comment]
fixed by @grs in https://github.com/grs/rhea/commit/d86d698bf229bf9db14b424659faf7c08ecbe092
