### ISSUE TITLE
link fields source as nested object test case fails

### ISSUE THREAD

**Issue by g0dd4rd** [grs/rhea#4]
Description:
While running the TCs in Jenkins, the "link fields source as nested object" test case fails.

Steps to reproduce:
1. mocha -g nested $rhea_inst_root/test/links.js

Actual results:
[connection-3] error: Error: connect ECONNRESET
[connection-3] disconnected
Scheduled reconnect in 100ms
․․

  3 passing (37ms)
  1 failing

  1) link fields source as nested object:
     Uncaught TypeError: value is out of bounds
      at TypeError (<anonymous>)
      at checkInt (buffer.js:705:11)
      at Buffer.writeUInt32BE (buffer.js:748:5)
      at Function.write_ulong [as write] (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:164:12)
      at types.Writer.write_fixed_width (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:584:14)
      at types.Writer.write_value (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:626:14)
      at types.Writer.write (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:618:10)
      at types.Writer.write_constructor (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:608:14)
      at types.Writer.write (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:617:10)
      at types.Writer.write_compound (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:653:18)
      at types.Writer.write_value (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:630:14)
      at types.Writer.write (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:618:10)
      at types.Writer.write_compound (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:653:18)
      at types.Writer.write_value (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:630:14)
      at types.Writer.write (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:618:10)
      at types.Writer.write_compound (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:653:18)
      at types.Writer.write_value (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:630:14)
      at types.Writer.write (/home/jprajzne/nodejs/node_modules/rhea/lib/types.js:618:10)
      at Object.frames.write_frame (/home/jprajzne/nodejs/node_modules/rhea/lib/frames.js:105:16)
      at Transport.encode (/home/jprajzne/nodejs/node_modules/rhea/lib/transport.js:43:25)
      at Connection._write_frame (/home/jprajzne/nodejs/node_modules/rhea/lib/connection.js:438:25)
      at Session.output (/home/jprajzne/nodejs/node_modules/rhea/lib/session.js:373:21)
      at link._process (/home/jprajzne/nodejs/node_modules/rhea/lib/link.js:89:26)
      at Session._process (/home/jprajzne/nodejs/node_modules/rhea/lib/session.js:459:27)
      at Connection._process (/home/jprajzne/nodejs/node_modules/rhea/lib/connection.js:429:39)
      at process._tickCallback (node.js:442:13)

Expected results:
The TC passes.

Note:
This TC fails with and without JBoss A-MQ 6.2.0 GA running with AMQP transport.

**Comment by grs** [comment]
What version of node is the failure occurring on, do you know?

**Comment by g0dd4rd** [comment]
It's node v0.10.36
